### ISSUE TITLE
请问yac的info其中几个字段的含义

### ISSUE THREAD

**Issue by egege** [laruence/yac#100]
Array
(
    [memory_size] => 71303168
    [slots_memory_size] => 4194304
    [values_memory_size] => 67108864
    [segment_size] => 4194304
    [segment_num] => 16
    [miss] => 2
    [hits] => 2
    [fails] => 0
    [kicks] => 0
    [recycles] => 0
    [slots_size] => 32768
    [slots_used] => 1
)
segment_size（看了一下大家的返回都和slots_memory_size大小都一样？），segment_num，fails（什么情况下会失败？），recycles（看一个issue说是内存重新分配的次数，什么情况下会发生？）

**Comment by laruence** [comment]
segment_size是内存分块大小，segment_num是申请了多少块，fails，获取到错误的数据的次数（crc校验不通过），recycles segment用完了会导致重新分配。
