### ISSUE TITLE
Serializer choice at runtime

### ISSUE THREAD

**Issue by remicollet** [laruence/yac#107]
It will be nice to be able to select serializer at runtime.

For now we have to select **php** or **msgpack** at buildtime, which is not friendly for downstream binary distribution (RPM or Windows DLL or any other)

And probably easier to extend later to additional serializer, like igbinary...

**Comment by laruence** [comment]
hmm, yeah, that is in plan, it should be not difficult to do that, just, since it only affects transfering data between local memory and shared memory , so different serializer makes not much difference in performance..

**Comment by laruence** [comment]
it has been merged, I also added json support.
anyway,  I made a little change
```
1.  bring YAC_SERIALIZER back
2. determine the serializer/unserialize at MINIT
```
thanks
