### ISSUE TITLE
Cli模式下，获取不到缓存，每次执行都在写缓存，是需要特殊配置吗？

### ISSUE THREAD

**Issue by MsZhu** [laruence/yac#113]
if (!($test = $yac->get('test'))) {
    var_dump($yac->set('test', 123));
}
var_dump($test);

**Comment by laruence** [comment]
因为cli的生命期就是运行一次，运行完了就退出了啊

**Comment by MsZhu** [comment]
> 因为cli的生命期就是运行一次，运行完了就退出了啊

哦，原来如此，，yac跟php进程绑定在一起可以，要是缓存的数据不与进程捆绑就可以相对持久化了~
