### ISSUE TITLE
Warning: Yac::get(): Unserialization failed

### ISSUE THREAD

**Issue by RamboLau** [laruence/yac#57]
这个错误是由什么引起的？

**Comment by laruence** [comment]
一般是因为数据写花了导致的,  应该把这个警告给禁掉. 回头处理下.

**Comment by RamboLau** [comment]
Warning: Yac::get(): Decompression failed

还有这种解压失败的。。。

**Comment by laruence** [comment]
忽略即可, 应该感谢这些警告, 才不会把写花的数据当做正确数据

**Comment by gouchaoer** [comment]
其实这种极小概率的出错warning并没问题，自己处理可以设置handler把warning抛出成异常再处理

**Comment by itbdw** [comment]
Hey, actually, this is expected behaviors, yac is a lockless cache, that is why it is so fast and also has some issues like this.but this(the warnings you saw) also is a protection for preventing wrong data goes to user script.to reduce this warnings: you need try to avoid or reduce the probability of multiple processes seting one key. increase the slots size, or you can increase the crc bytes(I will add a configuration in php.ini for this later).thanks
--

[https://github.com/laruence/yac/issues/23#issuecomment-22808078](url)
