### ISSUE TITLE
鸟哥Mac上编译出错

### ISSUE THREAD

**Issue by Anoxia** [laruence/yac#60]
编译Yac时出现下面问题：
 cc -I. -I/Users/Anoxia/Downloads/yac-2.0.0 -DPHP_ATOM_INC -I/Users/Anoxia/Downloads/yac-2.0.0/include -I/Users/Anoxia/Downloads/yac-2.0.0/main -I/Users/Anoxi
a/Downloads/yac-2.0.0 -I/usr/local/Cellar/php56/5.6.17/include/php -I/usr/local/Cellar/php56/5.6.17/include/php/main -I/usr/local/Cellar/php56/5.6.17/include/
php/TSRM -I/usr/local/Cellar/php56/5.6.17/include/php/Zend -I/usr/local/Cellar/php56/5.6.17/include/php/ext -I/usr/local/Cellar/php56/5.6.17/include/php/ext/d
ate/lib -DHAVE_CONFIG_H -g -O0 -c /Users/Anoxia/Downloads/yac-2.0.0/yac.c  -fno-common -DPIC -o .libs/yac.o
/Users/Anoxia/Downloads/yac-2.0.0/yac.c:30:10: fatal error: 'zend_smart_str.h' file not found

**Comment by Anoxia** [comment]
找到问题的原因了，是我下错了版本，最新本是针对PHP7的，您最好在PECL标注一下

**Comment by laruence** [comment]
如果你是通过pecl安装, 他会选择正确的版本.... 不过, 你说的也对, 我想想怎加个限制

**Comment by lovechunqiu** [comment]
这个问题解决了么？
