### ISSUE TITLE
#include "ext/standard/php_smart_str.h"

### ISSUE THREAD

**Issue by ice6** [laruence/yac#63]
php7下尝试ENABLE_MSGPACK，然后报ext/standard/php_smart_str.h file not found错误。请问是不是php7默认的序列化/反序列化效率大增，已经没有enable msgpack的必要了？

**Comment by laruence** [comment]
如果是PHP7, 就用yar php7分支的代码, 不要用master分支的代码

**Comment by ice6** [comment]
@laruence 我的环境是php7.0.5,使用phpbrew安装yac 2.0.0这个版本。我看了https://github.com/laruence/yac/blob/php7/serializer/msgpack.c 这个文件 和 https://github.com/laruence/yac/blob/master/serializer/msgpack.c 这个文件，里面都有这行代码：
`#include "ext/standard/php_smart_str.h" `，这行代码报错，所以是不是我少安装什么包了？

**Comment by laruence** [comment]
hmm, 那有可能是bug, 稍微晚点我看下...

**Comment by ice6** [comment]
@laruence 多谢，辛苦了。
