### ISSUE TITLE
按照文档提示设置

### ISSUE THREAD

**Issue by guanhui07** [laruence/yac#65]
key 保存不进去。

<?php
$yac = new Yac();
$yac->set("foo", "bar");
$yac->set(
    array(
        "dummy" => "foo",
        "dummy2" => "foo",
        )
    );
var_dump($yac->get("dummy"));

获取到是false ,文档中提示的常量是可以打印的。

**Comment by iou402** [comment]
问题解决了吗? 我目前遇到的也是这样的问题

**Comment by Izzyyang** [comment]
$yac=new Yac();
var_dump($yac->info());
yac：0.9.2
直接返回false，无法设值。求教。中间安装过2.0.1build失败后换了0.9.2.

**Comment by laruence** [comment]
你yac.enable=1设置了么

**Comment by laruence** [comment]
另外注意看日志, 是不是启动的时候报错了
