### ISSUE TITLE
flush() 方法不够友好

### ISSUE THREAD

**Issue by breath-co2** [laruence/yac#67]
如果有2个对象：

``` php
$yac1 = new Yac('a');
$yac1->set('test', 'a');
$yac2 = new Yac('b');
$yac2->set('test', 'b');

$yac1->flush();
var_dump($yac2->get('test'));    // false
```

任意一个对象执行 flush() 操作，则会清空所有数据，包括其它对象的数据，这样是不是不够“友好”？
当然，我明白 new Yac() 里的参数只是一个前缀的区别，然而使用 `Yac::flush()` 这样执行会报错，这并不是一个静态方法，必须 `$yac->flush()` 这样执行，这种调用方法往往程序开发会认为是清空当前对象的数据，而不是整个yac数据

**Comment by laruence** [comment]
这个是实现的限制， Yac并没有办法知道当前前缀的key都有哪些.

**Comment by yuweitaocn** [comment]
那就FLUSH改成FLASHALL不是就好了@LARUENCE

**Comment by laruence** [comment]
http://php.net/manual/en/memcached.flush.php
