### ISSUE TITLE
php 5.6.22 下编译不通过

### ISSUE THREAD

**Issue by xluohome** [laruence/yac#71]
下载 https://pecl.php.net/get/yac-2.0.1.tgz

make 时出现如下错误：
/bin/sh /root/yac-2.0.1/libtool --mode=compile cc  -I. -I/root/yac-2.0.1 -DPHP_ATOM_INC -I/root/yac-2.0.1/include -I/root/yac-2.0.1/main -I/root/yac-2.0.1 -I/usr/local/php5.6.22/include/php -I/usr/local/php5.6.22/include/php/main -I/usr/local/php5.6.22/include/php/TSRM -I/usr/local/php5.6.22/include/php/Zend -I/usr/local/php5.6.22/include/php/ext -I/usr/local/php5.6.22/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/yac-2.0.1/yac.c -o yac.lo
mkdir .libs
 cc -I. -I/root/yac-2.0.1 -DPHP_ATOM_INC -I/root/yac-2.0.1/include -I/root/yac-2.0.1/main -I/root/yac-2.0.1 -I/usr/local/php5.6.22/include/php -I/usr/local/php5.6.22/include/php/main -I/usr/local/php5.6.22/include/php/TSRM -I/usr/local/php5.6.22/include/php/Zend -I/usr/local/php5.6.22/include/php/ext -I/usr/local/php5.6.22/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/yac-2.0.1/yac.c  -fPIC -DPIC -o .libs/yac.o
/root/yac-2.0.1/yac.c:30:28: error: zend_smart_str.h: No such file or directory
In file included from /root/yac-2.0.1/yac.c:35:
/root/yac-2.0.1/serializer/yac_serializer.h:28: error: expected declaration specifiers or ‘...’ before ‘smart_str’
/root/yac-2.0.1/yac.c: In function ‘OnChangeKeysMemoryLimit’:
/root/yac-2.0.1/yac.c:82: warning: passing argument 1 of ‘zend_atol’ makes pointer from integer without a cast
/usr/local/php5.6.22/include/php/Zend/zend_operators.h:377: note: expected ‘const char _’ but argument is of type ‘int’
/root/yac-2.0.1/yac.c: In function ‘OnChangeValsMemoryLimit’:
/root/yac-2.0.1/yac.c:90: warning: passing argument 1 of ‘zend_atol’ makes pointer from integer without a cast
/usr/local/php5.6.22/include/php/Zend/zend_operators.h:377: note: expected ‘const char *’ but argument is of type ‘int’
/root/yac-2.0.1/yac.c: In function ‘OnChangeCompressThreshold’:
/root/yac-2.0.1/yac.c:98: warning: passing argument 1 of ‘zend_atol’ makes pointer from integer without a cast
/usr/local/php5.6.22/include/php/Zend/zend_operators.h:377: note: expected ‘const char *’ but argument is of type ‘int’
/root/yac-2.0.1/yac.c: At top level:
/root/yac-2.0.1/yac.c:119: error: expected ‘)’ before ‘_’ token
/root/yac-2.0.1/yac.c:270: error: expected ‘)’ before ‘_’ token
/root/yac-2.0.1/yac.c:299: error: expected ‘)’ before ‘_’ token
/root/yac-2.0.1/yac.c:366:38: error: macro "ZVAL_STRINGL" requires 4 arguments, but only 3 given
/root/yac-2.0.1/yac.c:370:34: error: macro "ZVAL_STRINGL" requires 4 arguments, but only 3 given
/root/yac-2.0.1/yac.c:426: error: expected ‘)’ before ‘_’ token
/root/yac-2.0.1/yac.c: In function ‘yac_delete_multi_impl’:
/root/yac-2.0.1/yac.c:493: error: expected ‘;’ before ‘{’ token
/root/yac-2.0.1/yac.c: In function ‘zim_yac___construct’:
/root/yac-2.0.1/yac.c:514: error: ‘zend_string’ undeclared (first use in this function)
/root/yac-2.0.1/yac.c:514: error: (Each undeclared identifier is reported only once
/root/yac-2.0.1/yac.c:514: error: for each function it appears in.)
/root/yac-2.0.1/yac.c:514: error: ‘prefix’ undeclared (first use in this function)
/root/yac-2.0.1/yac.c: In function ‘zim_yac_add’:
/root/yac-2.0.1/yac.c:573: error: too many arguments to function ‘zend_read_property’
/root/yac-2.0.1/yac.c:581: error: too few arguments to function ‘zend_make_printable_zval’
/root/yac-2.0.1/yac.c: In function ‘zim_yac_set’:
/root/yac-2.0.1/yac.c:630: error: too many arguments to function ‘zend_read_property’
/root/yac-2.0.1/yac.c:638: error: too few arguments to function ‘zend_make_printable_zval’
/root/yac-2.0.1/yac.c: In function ‘zim_yac___set’:
/root/yac-2.0.1/yac.c:650: error: ‘zend_string’ undeclared (first use in this function)
/root/yac-2.0.1/yac.c:650: error: ‘key’ undeclared (first use in this function)
/root/yac-2.0.1/yac.c:661: error: too many arguments to function ‘zend_read_property’
/root/yac-2.0.1/yac.c: In function ‘zim_yac_get’:
/root/yac-2.0.1/yac.c:681: error: too many arguments to function ‘zend_read_property’
/root/yac-2.0.1/yac.c:684: warning: assignment makes pointer from integer without a cast
/root/yac-2.0.1/yac.c:686: warning: assignment makes pointer from integer without a cast
/root/yac-2.0.1/yac.c:689: error: too few arguments to function ‘zend_make_printable_zval’
/root/yac-2.0.1/yac.c:690: warning: assignment makes pointer from integer without a cast
/root/yac-2.0.1/yac.c: In function ‘zim_yac___get’:
/root/yac-2.0.1/yac.c:704: error: ‘zend_string’ undeclared (first use in this function)
/root/yac-2.0.1/yac.c:704: error: ‘key’ undeclared (first use in this function)
/root/yac-2.0.1/yac.c:715: error: too many arguments to function ‘zend_read_property’
/root/yac-2.0.1/yac.c: In function ‘zim_yac_delete’:
/root/yac-2.0.1/yac.c:739: error: too many arguments to function ‘zend_read_property’
/root/yac-2.0.1/yac.c:749: error: too few arguments to function ‘zend_make_printable_zval’
/root/yac-2.0.1/yac.c:829:47: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
/root/yac-2.0.1/yac.c: In function ‘zim_yac_dump’:
/root/yac-2.0.1/yac.c:829: error: ‘add_assoc_string’ undeclared (first use in this function)
make: *_\* [yac.lo] Error 1

**Comment by xluohome** [comment]
知道原因了， 2.X 版本的 只适合 php 7+  ，  下载了 0.9.2 版本 可以编译通过了，   这些都是beta 版本 有用在生产环境的吗？

**Comment by laruence** [comment]
2.x只是给7用的， 0.9.2版本是给php5用的，一直在微博用

**Comment by laruence** [comment]
你也可以用php5分支
