### ISSUE TITLE
docker php:7-fpm-alpine install yac-2.0.1

### ISSUE THREAD

**Issue by cq-z** [laruence/yac#73]
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
**expr: syntax error
./configure: line 2519: test: =: unary operator expected
expr: syntax error
./configure: line 2526: test: =: unary operator expected
expr: syntax error
./configure: line 2533: test: =: unary operator expected**
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no

提示错误
expr: syntax error
./configure: line 2519: test: =: unary operator expected
expr: syntax error
./configure: line 2526: test: =: unary operator expected
expr: syntax error
./configure: line 2533: test: =: unary operator expected
不知道会有影响吗？

**Comment by cq-z** [comment]
gcc版本信息：
(1/22) Installing m4 (1.4.17-r1)
(2/22) Installing perl (5.22.2-r0)
(3/22) Installing autoconf (2.69-r0)
(4/22) Installing libmagic (5.27-r0)
(5/22) Installing file (5.27-r0)
(6/22) Installing libgcc (5.3.0-r0)
(7/22) Installing libstdc++ (5.3.0-r0)
(8/22) Installing binutils-libs (2.26-r0)
(9/22) Installing binutils (2.26-r0)
(10/22) Installing gmp (6.1.0-r0)
(11/22) Installing isl (0.14.1-r0)
(12/22) Installing libgomp (5.3.0-r0)
(13/22) Installing libatomic (5.3.0-r0)
(14/22) Installing mpfr3 (3.1.2-r0)
(15/22) Installing mpc1 (1.0.3-r0)
(16/22) Installing gcc (5.3.0-r0)
(17/22) Installing musl-dev (1.1.14-r11)
(18/22) Installing libc-dev (0.7-r0)
(19/22) Installing g++ (5.3.0-r0)
(20/22) Installing make (4.1-r1)
(21/22) Installing re2c (0.14.3-r0)
(22/22) Installing .phpize-deps (0)
系统信息：
bash-4.3# cat /etc/issue
Welcome to Alpine Linux 3.4
Kernel \r on an \m (\l)

**Comment by laruence** [comment]
如果编译成功, 并且make test通过, 就不存在问题

**Comment by cq-z** [comment]
编译是成功的，测试了下目前运行也是没报错的。谢谢鸟哥
