### ISSUE TITLE
wsl ubuntu16.04 php7.3.3 使用pecl 安装yac2.0.2 报错  recipe for target 'yac.lo' failed

### ISSUE THREAD

**Issue by lgarfield** [laruence/yac#95]
Makefile:194: recipe for target 'yac.lo' failed
make: *** [yac.lo] Error 1
ERROR: `make' failed

哪位大大能帮忙解决一下，感激不尽。

**Comment by laruence** [comment]
可以下载pecl的安装包自己编译
