### ISSUE TITLE
php 7.3.4 make 错误

### ISSUE THREAD

**Issue by liuyanqiang** [laruence/yac#96]
/bin/sh /data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/libtool --mode=compile cc  -I. -I/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2 -DPHP_ATOM_INC -I/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/include -I/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/main -I/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2 -I/home/liuyanqiang/msuf/php/include/php -I/home/liuyanqiang/msuf/php/include/php/main -I/home/liuyanqiang/msuf/php/include/php/TSRM -I/home/liuyanqiang/msuf/php/include/php/Zend -I/home/liuyanqiang/msuf/php/include/php/ext -I/home/liuyanqiang/msuf/php/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/yac.c -o yac.lo
mkdir .libs
 cc -I. -I/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2 -DPHP_ATOM_INC -I/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/include -I/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/main -I/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2 -I/home/liuyanqiang/msuf/php/include/php -I/home/liuyanqiang/msuf/php/include/php/main -I/home/liuyanqiang/msuf/php/include/php/TSRM -I/home/liuyanqiang/msuf/php/include/php/Zend -I/home/liuyanqiang/msuf/php/include/php/ext -I/home/liuyanqiang/msuf/php/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/yac.c  -fPIC -DPIC -o .libs/yac.o
/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/yac.c: 在函数‘yac_add_impl’中:
/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/yac.c:150:8: 错误：‘IS_CONSTANT’未声明(在此函数内第一次使用)
   case IS_CONSTANT:
        ^
/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/yac.c:150:8: 附注：每个未声明的标识符在其出现的函数内只报告一次
/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/yac.c: 在函数‘yac_get_impl’中:
/data/liuyanqiang/msuf/init/sources/yac-yac-2.0.2/yac.c:350:9: 错误：‘IS_CONSTANT’未声明(在此函数内第一次使用)

**Comment by bb7788** [comment]
@liuyanqiang 同样的问题 php7.3.7 有解决么
@laruence

**Comment by bb7788** [comment]
刚看到修复了，使用master分支的代码可以编译通过
